
application: scrambleface
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /files/js
  static_dir: files/js

- url: /files/css
  static_dir: files/css

- url: /files/images
  static_dir: files/images

- url: /
  static_files: files/index.html
  upload: files/index.html
  
- url: /.*
  script: api.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: PIL
  version: latest

